Home screen with beehives backend
4chiAA/capstone-beenabler pull request #3
Opened 2024-01-11 15:41 UTC by 4chiAA

2024-01-11 17:21 UTC, MoinMarcell requested changes
Nice Job so far, some recommendations below! It is historical that at the end of a file there needs to be a new line for some reason while compiling. You can read about it [here](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file)

2024-01-11 17:21 UTC, MoinMarcell commented on backend/pom.xml
> +		</dependency>
There is a newer Version, check out Slack, Sara posted the correct Version :)

2024-01-11 17:21 UTC, MoinMarcell commented on backend/src/main/java/com/beenabler/backend/controller/BeehiveController.java
> +@RequestMapping("/api")
```suggestion
@RequestMapping("/api/beehives")
```

2024-01-11 17:21 UTC, MoinMarcell commented on backend/src/main/java/com/beenabler/backend/controller/BeehiveController.java
> +    @GetMapping("/beehives")
```suggestion
    @GetMapping
```

2024-01-11 17:21 UTC, MoinMarcell commented on backend/src/main/java/com/beenabler/backend/model/Beehive.java
> +}
No new line at end of file

2024-01-11 17:21 UTC, MoinMarcell commented on backend/src/main/java/com/beenabler/backend/model/BeehiveType.java
> +}
No new line at end of file

2024-01-11 17:21 UTC, MoinMarcell commented on backend/src/main/java/com/beenabler/backend/repo/BeehiveRepo.java
> +@Repository
You don´t need the annotation, because it is already included in the MongoRepository
```suggestion
```

2024-01-11 17:21 UTC, MoinMarcell commented on backend/src/test/java/com/beenabler/backend/controller/BeehiveControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.get(BASE_URL+"/beehives"))
```suggestion
        mockMvc.perform(MockMvcRequestBuilders.get(BASE_URL))
```

2024-01-11 17:21 UTC, MoinMarcell commented on backend/src/test/java/com/beenabler/backend/controller/BeehiveControllerTest.java
> +    private final String BASE_URL = "/api";
```suggestion
    private final String BASE_URL = "/api/beehives";
```

2024-01-11 17:21 UTC, MoinMarcell commented on backend/src/test/resources/application.properties
> +de.flapdoodle.mongodb.embedded.version=7.0.0
No new line at end of file

2024-01-11 17:39 UTC, 4chiAA commented on backend/src/test/java/com/beenabler/backend/controller/BeehiveControllerTest.java
> +    private final String BASE_URL = "/api";
> 

Later I want to include GetMapping for single beehives, which would be /api/beehive/{id}

2024-01-12 08:55 UTC, MoinMarcell requested changes

2024-01-12 08:55 UTC, MoinMarcell commented on backend/src/main/java/com/beenabler/backend/controller/BeehiveController.java
It is not best practice to set the URI like this "/api" only and set the "/behivees" to the GetMapping. You will need to set at every Endpoint than "/behivees" instead of setting it only onetime

2024-01-12 12:10 UTC, lostspezi approved these changes
LGTM!:)

2024-01-12 12:10 UTC, merged